### PR TITLE
Multibyte compatibility for str::encode()

### PR DESCRIPTION
**Pull request by lukasbestle**

### CODE REVIEW

**Comment by bastianallgeier** [comment]
Might be a stupid question, but what exactly does it do? :)

**Comment by lukasbestle** [comment]
Well, it supports UTF-8 strings now. Before this change it encoded each byte separately, which breaks everything. :)

**Comment by bastianallgeier** [comment]
Ok, sounds useful :P

**Comment by lukasbestle** [comment]
:+1:

**Pull request merged**
