### PR TITLE
Implement secure str::random and non-secure str::quickRandom

### LINKED ISSUE #153: Secure str::random
Maybe a more secure `str::random` function should be considered since it is used to generate the [authentication key](https://github.com/getkirby/kirby/blob/d93de5fb29b3f1dc32f941cf46b6efdc27f3ba7a/core/user.php#L145) or [CSRF tokens](https://github.com/getkirby/panel/blob/606b782e9ccd454cc732668a7f73ab19bbd98d52/app/src/panel.php#L200).

What do you think about implementing a [random](https://github.com/laravel/framework/blob/1dfb03cb4b960e1f5d4a5f7b81f39f5cb5f9e731/src/Illuminate/Support/Str.php#L223-L236) function based on [`random_bytes`](http://php.net/manual/en/function.random-bytes.php) and a [quickRandom](https://github.com/laravel/framework/blob/1dfb03cb4b960e1f5d4a5f7b81f39f5cb5f9e731/src/Illuminate/Support/Str.php#L259-L264) function for insecure stuff like Laravel does?

### PR DESCRIPTION
**Pull request by mzur**
`str::random` can now be used for cryptographic purposes while `str::quickRandom` is a faster alternative for everything else.

Note that `str::random` now requires the PCRE extension. If this shouldn't be a requirement the function needs to be changed again before merging.

Closes #153

### CODE REVIEW

**Comment by mzur** [comment]
Well, I did not consider that the native implementation of `random_bytes` exists only since PHP 7.0. To support PHP >= 5.2 [paragonie/random_compat](https://github.com/paragonie/random_compat) would be required as an additional dependency.

**Comment by lukasbestle** [comment]
To be honest I don't think we should introduce another dependency for this. One way would be to fall back to the old behavior if the function is not available.

Another thing: Code that uses `str::random` will default to the secure behavior with your solution. While that's great for security, it might harm performance as most use-cases for `str::random` don't require cryptographically secure random strings.

**Comment by mzur** [comment]
> To be honest I don't think we should introduce another dependency for this. One way would be to fall back to the old behavior if the function is not available.

Fair enough. I wasn't aware of `random_bytes` not being available in PHP <7.0 when I opened this PR.

> Code that uses str::random will default to the secure behavior with your solution. While that's great for security, it might harm performance as most use-cases for str::random don't require cryptographically secure random strings.

Here I'd argue to better be safe than fast. [Kirby](https://github.com/getkirby/kirby/blob/d93de5fb29b3f1dc32f941cf46b6efdc27f3ba7a/core/user.php#L145) and the [Panel](https://github.com/getkirby/panel/blob/606b782e9ccd454cc732668a7f73ab19bbd98d52/app/src/panel.php#L200) use `str::random` in a context where security matters and plugin developers/toolkit users may have adapted this pattern. We rather should present `str:quickRandom` in the release notes and let developers decide where they _don't_ need secure random strings (and not where they _do_). What do you think?

**Comment by lukasbestle** [comment]
That's right. Have you tested how much slower the more secure version really is? If it's negligible, we can do it that way. However we should be doing this in the next minor release (2.4) as it's a breaking change.

**Comment by jenstornell** [comment]
Maybe it's possible to add an extra parameter like:

```php
str::random($args, $secure = false);
````

If set to true (not default) it will be more secure but require more power.

**Comment by mzur** [comment]
@lukasbestle As a quick benchmark, I ran this script:
```php
<?php

require __DIR__.'/bootstrap.php';

for ($i = 0; $i < 100000; $i++) {
   str::random(32, 'alpha');
}
```
With the original `random`, the proposed `random` and the proposed `quickRandom`, each with `alphaUpper`, `alphaLower`, `alphaNum`, `alpha` and `num`, and measured the "real" time with `time php script.php` (in seconds):

|   | alphaUpper | alphaLower | alphaNum | alpha | num |
|---| ---------- | ---------- | -------- | ----- | --- |
| **random_old** | 03.59 | 03.43 | 05.29 | 04.33 | 03.75 |
| **random_new** | 02.58 | 02.46 | 02.92 | 02.26 | 05.09 |
| **quickRandom** | 01.85 | 01.88 | 05.02 | 03.86 | 01.16 |

`random_old` and `quickRandom` seem to perform worse with more available characters whereas `random_new` performs worse with fewer available characters (which makes sense).

It's not a very good benchmark but you can try and see if you get similar results. I run PHP 7.0.8 with Xdebug v2.4.0.

@jenstornell Well, then we could make a `random` and `secureRandom` function instead of `random` and `quickRandom` as well.

**Comment by lukasbestle** [comment]
Thank you very much for the benchmarks. It looks like the more secure version is actually faster for most use-cases. Probably because it uses a native function instead of PHP code. We will consider this for 2.4.

**Comment by mzur** [comment]
I've removed paragonie/random_compat again. `str::random` will now fall back to `str::quickRandom` for PHP <7.0.

**Comment by lukasbestle** [comment]
This is now implemented on the `develop` branch. Thank you very much.

**Pull request closed without merging**
