### PR TITLE
Add a generic file extension for source code

### PR DESCRIPTION
**Pull request by fanningert**
This very helpfully for source code with not file extension like ABAP.

### CODE REVIEW

**Comment by bastianallgeier** [comment]
Sorry for the delay. I'm not sure I get this 100%. Why would you not just add html as extension to such files?

**Comment by fanningert** [comment]
You are right I can convert the file extension to html. But for other user it is easy to view that the file has source code as content. And it is markt as source code in kirby. txt would be a alternative, but this extension is reserved by kirby for metadata. I think the html extension is for HTML, php extension is for PHP, ...
But I can live without this feature. I wrote in the mean time a own kirby extension for display source code. But it is possible to add a file extension to a file group (image, source code, ...) via a extension?

**Comment by fanningert** [comment]
Ok, I found the solution. the file extension and the file groups are static variables. so it should possible to add a own file extensnion to a file group.

**Comment by bastianallgeier** [comment]
yes, very easily. Just extend f::$mimes and f::$types in your config and you are all good.

**Pull request closed without merging**
