### PR TITLE
Group by callback

### PR DESCRIPTION
**Pull request by FabianSperrle**
Forum discussion: https://forum.getkirby.com/t/pages-groupby-with-callback/2607

### CODE REVIEW

**Comment by bastianallgeier** [comment]
As I already wrote on your other PR, I'm going to implement that a bit differently, but it will definitely land in 2.3

**Comment by bastianallgeier** [comment]
After I started to implement this on my own I realized that your version is actually perfect :) Sorry for closing it too quickly. I don't know exactly what I was thinking. I just added it to a feature branch: https://github.com/getkirby/toolkit/tree/feature/groupByCallback

**Comment by FabianSperrle** [comment]
No worries. I restored the branch on the kirby repository, in case you want to merge that as well. Or did you find a nicer solution for solving the type problem with pages/children?

**Comment by bastianallgeier** [comment]
I'm still on it.

**Comment by bastianallgeier** [comment]
I think I found a good way. There's no also a feature branch in the kirby repository.

**Comment by distantnative** [comment]
:+1:

**Pull request closed without merging**
