### PR TITLE
Added redis cache driver

### PR DESCRIPTION
**Pull request by nblackburn**
Appolgies for the vendor files, normally you wouldn't have them in the repo but because they have been included, i had to recompile the auto-loader for this to work out of the box.

### CODE REVIEW

**Comment by lukasbestle** [comment]
Thanks for sharing! I haven't tested this yet, but the code looks good.

However I think it makes sense to publish this as a plugin instead. Installing predis by default even if the Redis cache isn't used by all users isn't optimal.

**Comment by nblackburn** [comment]
How would i go about turning this into a plugin?

**Comment by nblackburn** [comment]
@lukasbestle Looking at the code, it doesn't look like you can extend it.

**Comment by lukasbestle** [comment]
See my comment in #230.

**Pull request closed without merging**
